# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79065491687b6a39de373384ed458b936384590a570dd88ed5a80b1e7cf0c3c6738dac516871fab55f87b02fe0e59d10ee66b3045667db28e4074b9f04712ecb

test:
  secret_key_base: 0b77699cd04b49c4245fd12f48172b5433e2fadc9dfb71bc3c65be757d2e3f8cb355b2f5bfd6e041f6e5327efc00c50205767a52f882835d9e003e68bea9c2b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
